apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  type: ClusterIP
  selector:
    deployment: elastic-search
  ports:
    -
      name: http-1
      protocol: TCP
      port: 9200
    -
      name: http-2
      protocol: TCP
      port: 9300