apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
      deployment: kibana
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: kibana
        deployment: kibana
    spec:
      #initContainers:
      #- name: init-elasticsearch-service
       # image: busybox
        #command: ['sh', '-c', 'until nslookup elasticsearch-service; do echo waiting for elasticsearch-service; sleep 2; done;']
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.11.0
        livenessProbe:
          tcpSocket:
            port: 5601
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/status
            port: http
          initialDelaySeconds: 50
          periodSeconds: 5
        imagePullPolicy: Always
        ports:
        -
          containerPort: 5601
          protocol: "TCP"
          name: http
        volumeMounts:
        - name: kibana-yml
          mountPath: /usr/share/kibana/config/kibana.yml
          subPath: kibana.yml
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
             fieldPath: status.podIP
      volumes:
      - name: kibana-yml
        configMap:
          name: kibana-yml
