apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: firas1234/customer-mk:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_INCLUDE
              value: "kubernetes"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: customer
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: customer
                  key: password
          resources:
            requests:
              cpu: "0.2"
              memory: 800Mi
            limits:
              cpu: "1.0"
              memory: 800Mi
          volumeMounts:
            - name: customer-volume
              mountPath: /etc/secretspot
      volumes:
        - name: customer-volume
          secret:
            secretName: customer
      serviceAccountName: api-service-account